server:
  error:
    include-stacktrace: on_param

#security:
#  config:
#    expiration: 3600000
#    prefix: Bearer
#    key: SECRET_KEY

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true